-- Enable RLS
alter table if exists "public"."matches" enable row level security;
alter table if exists "public"."standings" enable row level security;
alter table if exists "public"."app_cache" enable row level security;

-- Create app_cache table
create table if not exists "public"."app_cache" (
    "id" text not null default '1',
    "data" jsonb not null,
    "last_updated" timestamp with time zone default now(),
    constraint "app_cache_pkey" primary key ("id")
);

-- Policies for app_cache
create policy "Enable read access for all users" on "public"."app_cache"
as permissive for select
to public
using (true);

create policy "Enable insert/update for service role only" on "public"."app_cache"
as permissive for all
to service_role
using (true)
with check (true);

-- Create matches table (Optional, for granular queries if needed later)
create table if not exists "public"."matches" (
    "id" bigint not null,
    "utc_date" timestamp with time zone,
    "status" text,
    "data" jsonb, -- Store full match object
    constraint "matches_pkey" primary key ("id")
);

-- Policies for matches
create policy "Enable read access for all users" on "public"."matches"
as permissive for select
to public
using (true);

create policy "Enable all access for service role" on "public"."matches"
as permissive for all
to service_role
using (true)
with check (true);

-- Create standings table
create table if not exists "public"."standings" (
    "id" bigint generated by default as identity,
    "league" text not null, -- 'La Liga', 'Champions League'
    "data" jsonb, -- Store full standing object
    constraint "standings_pkey" primary key ("id")
);

-- Policies for standings
create policy "Enable read access for all users" on "public"."standings"
as permissive for select
to public
using (true);

create policy "Enable all access for service role" on "public"."standings"
as permissive for all
to service_role
using (true)
with check (true);
